version: "2"
services:
  fritz-mrtg:
    build: .
    hostname: mrtg
    restart: always
    ports:
      - "8880:80"
    volumes:
      - "./conf.d:/etc/mrtg/conf.d"
      - "./html:/usr/share/nginx/html"
    environment:
        TZ: "Europe/Berlin"
        HOSTS: 'public:192.168.178.1'
    tmpfs:
      - "/run"
